routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    \Auth::logout();
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/list', 'User\UserController@list')->name('list');
    Route::get('/getAllUsers', 'User\UserController@getAllUsers')->name('getAllUsers');
    Route::get('/profile', 'User\UserController@profile')->name('profile');
});

Route::group(['prefix' => 'family', 'as' => 'family.'], function(){
    Route::get('/', 'Family\FamilyController@view')->name('view');
    Route::get('/getAll', 'Family\FamilyController@getAll')->name('getAll');
    Route::post('/create', 'Family\FamilyController@create')->name('create');
    Route::post('/update', 'Family\FamilyController@update')->name('update');
    Route::get('/delete/{id}', 'Family\FamilyController@delete')->name('delete');
});


Route::group(['prefix' => 'product', 'as' => 'product.'], function (){
    Route::get('/', 'Products\ProductController@view')->name('view');
    Route::get('/getProducts', 'Products\ProductController@getProducts')->name('getProducts');
    Route::get('/getFamilies', 'Products\ProductController@getFamilies')->name('getFamilies');
    Route::post('/create', 'Products\ProductController@create')->name('create');
    Route::post('/update', 'Products\ProductController@update')->name('update');
    Route::get('/delete/{id}', 'Products\ProductController@delete')->name('delete');
});

Route::group(['prefix' => 'provincie', 'as' => 'provincie.'], function (){
    Route::get('/', 'Provincie\ProvincieController@view')->name('view');
    Route::get('/getAll', 'Provincie\ProvincieController@getAll')->name('getAll');
    Route::post('/create', 'Provincie\ProvincieController@create')->name('create');
    Route::post('/update', 'Provincie\ProvincieController@update')->name('update');
    Route::get('/delete/{id}', 'Provincie\ProvincieController@delete')->name('delete');
});

Route::group(['prefix' => 'zone', 'as' => 'zone.'], function (){
    Route::get('/', 'Zone\ZoneController@view')->name('view');
    Route::get('/getAll', 'Zone\ZoneController@getAll')->name('getAll');
    Route::get('/getProvincies', 'Zone\ZoneController@getProvincies')->name('getProvincies');
    Route::post('/create', 'Zone\ZoneController@create')->name('create');
    Route::post('/update', 'Zone\ZoneController@update')->name('update');
    Route::get('/delete/{id}', 'Zone\ZoneController@delete')->name('delete');
});

Route::group(['prefix' => 'community', 'as' => 'community.'], function (){
    Route::get('/', 'Community\CommunityController@view')->name('view');
    Route::get('/getAll', 'Community\CommunityController@getAll')->name('getAll');
    Route::post('/create', 'Community\CommunityController@create')->name('create');
    Route::post('/update', 'Community\CommunityController@update')->name('update');
    Route::get('/delete/{id}', 'Community\CommunityController@delete')->name('delete');
});

Route::group(['prefix' => 'client', 'as' => 'client.'], function () {
    Route::get('/', 'Client\ClientController@view')->name('view');
    Route::get('/getProvincie', 'Client\ClientController@getProvincie')->name('getProvincie');
    Route::get('/getClients', 'Client\ClientController@getClients')->name('getClients');
    Route::post('/create', 'Client\ClientController@saveClient')->name('create');
    Route::post('/updateClient', 'Client\ClientController@updateClient')->name('updateClient');
    Route::get('/delete/{id}', 'Client\ClientController@delete')->name('delete');
});

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.'], function (){
    Route::post('/uploadShopDiary', 'Dashboard\DashboardController@uploadShopDiary')->name('uploadShopDiary');
    Route::get('/getDairyReport', 'Dashboard\DashboardController@getDairyReport')->name('getDairyReport');
    Route::get('/getGraph/{type}', 'Dashboard\DashboardController@getGraph')->name('getGraph');
});

Route::group(['prefix' => 'reports', 'as' => 'reports.'], function (){
    Route::get('/', 'Reports\ReportsController@view')->name('view');
    Route::post('/filter', 'Reports\ReportsController@filterReport')->name('filter');
    Route::post('/export', 'Reports\ReportsController@exportReport')->name('export');
});

Route::group(['prefix' => 'users', 'as' => 'users.'], function (){ 
    Route::get('/', 'User\UserController@view')->name('view');
    Route::get('/lists', 'User\UserController@lists')->name('lists');
    Route::post('/create', 'User\UserController@createUser')->name('create');
    Route::post('/update', 'User\UserController@updateUser')->name('update');
    Route::post('/delete', 'User\UserController@deleteUser')->name('delete');
    Route::post('/changePassword', 'User\UserController@changePassword')->name('changePassword');
    Route::get('/resetPassword/{idUser}', 'User\UserController@resetPassword')->name('resetPassword');
});

resources/views/layouts/partials/footer.blade.php
    <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
        <span class="float-md-left d-block d-md-inline-block">Copyright &copy; 2019
            <a class="text-bold-800 grey darken-2" href="https://jgdigitalstudio.com" target="_blank">JG DIGITAL STUDIO</a>
        </span>
        <span class="float-md-right d-none d-lg-block">Hand-crafted & Made with<i class="ft-heart pink"></i>
            <span id="scroll-top"></span>
        </span>
    </p>

resources/views/layouts/partials/header.blade.php
<!-- BEGIN: Header-->
<nav class="header-navbar navbar-expand-lg navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-dark navbar-shadow bg-white">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-lg-none mr-auto"><a style="color: #009688;" class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item mr-auto">
                    <a class="navbar-brand" href="/home">
                        <img class="brand-logo" src="{{ asset('images/logo/logocfs.png') }}" alt="Cigar Family Spain" style="max-width:70px;">
                    </a>
                </li>
                <li class="nav-item d-none d-lg-block nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><!--<i class="toggle-icon ft-toggle-right font-medium-3" style="color:#2b2b2b;" data-ticon="ft-toggle-right"></i>--></a></li>
                <li class="nav-item d-lg-none"><a style="color: #009688;" class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="la la-ellipsis-v"></i></a></li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-expand" style="color:#2b2b2b;" href="#"><i class="ficon ft-maximize"></i></a></li>
                </ul>
                <ul class="nav navbar-nav float-right">
                    <li class="dropdown dropdown-user nav-item">
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            @auth
                                <span class="mr-1 user-name text-bold-700" style="color:#2b2b2b;">
                                    {{ auth()->user()->first_name }} {{ auth()->user()->last_name }}
                                </span>

                                <span class="avatar avatar-online">
                                @if(!is_null(auth()->user()->avatar))
                                        <img src="{{ asset('storage/users/' . auth()->user()->id . '/avatar/' . auth()->user()->avatar) }}" alt="avatar">
                                        <i></i>
                                    @else
                                        <img src="{{ asset('app-assets/images/no-avatar.png') }}" alt="avatar">
                                        <i></i>
                                    @endif
                                </span>
                            @endauth
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <!--<a class="dropdown-item" href="{{ route('user.profile')  }}">
                                <i class="ft-user" ></i> Mi Perfil
                            </a>
                            <div class="dropdown-divider"></div>-->
                            <a class="dropdown-item" href="{{ route('logout') }}">
                                <i class="ft-power"></i> Cerrar Sesión
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<!-- END: Header-->

resources/views/layouts/partials/sidebar.blade.php
<!-- BEGIN: Main Menu-->
<div class="main-menu menu-fixed menu-twl-cool-blue menu-accordion menu-shadow" data-scroll-to-active="true" style="touch-action: none; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            <li class="nav-item {{ request()->is('home') ? 'active' : '' }}">
                <a href="{{route('home')}}">
                    <i class="la la-dashboard"></i>
                    <span class="menu-title" data-i18n="eCommerce">
                        Escritorio
                    </span>
                </a>
            </li>

            <li class="nav-item {{ request()->is('reports') ? 'active' : '' }}">
                <a href="{{route('reports.view')}}">
                    <i class="la la-bar-chart"></i>
                    <span class="menu-title" data-i18n="eCommerce">
                        Informes
                    </span>
                </a>
            </li>

              <li class="nav-item has-sub">
                  <a href="#">
                      <i class="la la-users"></i>
                        <span class="menu-title" data-i18n="Usuarios">Usuarios</span>
                    </a>
                <ul class="menu-content" style="">
                    <li class="nav-item {{ request()->is('client') ? 'active' : '' }}">
                        <a href="{{route('client.view')}}">
                            <i class="fas fa-user-tie"></i>
                            <span class="menu-title" data-i18n="eCommerce">
                                Clientes
                            </span>
                        </a>
                    </li>
                    <li class="nav-item {{ request()->is('users') ? 'active' : '' }}">
                        <a href="{{route('users.view')}}">
                            <i class="fas fa-users"></i>
                            <span class="menu-title" data-i18n="eCommerce">
                                Equipo
                            </span>
                        </a>
                    </li>
                </ul>
              </li>

              <li class="nav-item has-sub">
                <a href="#"><i class="la la-gears"></i>
                    <span class="menu-title" data-i18n="Configuracion">Configuración</span>
                </a>
                <ul class="menu-content" style="">
                    <li class="nav-item {{ request()->is('family') ? 'active' : '' }}">
                        <a href="{{route('family.view')}}">
                            <i class="fas fa-smoking"></i>
                            <span class="menu-title" data-i18n="eCommerce">
                                Familias
                            </span>
                        </a>
                    </li>
                    <li class="nav-item {{ request()->is('product') ? 'active' : '' }}">
                        <a href="{{route('product.view')}}">
                            <i class="fad fa-shopping-cart"></i>
                            <span class="menu-title" data-i18n="eCommerce">
                                Productos
                            </span>
                        </a>
                    </li>
                    <li class="has-sub">
                        <a class="menu-item" href="#">
                            <i class="la la-street-view"></i>
                            <span data-i18n="Ubicaciones">Ubicaciones</span></a>
                        <ul class="menu-content">
                            <li class="nav-item {{ request()->is('provincie') ? 'active' : '' }}">
                                <a href="{{route('provincie.view')}}">
                                    <i class="fad fa-map-marker-check"></i>
                                    <span class="menu-title" data-i18n="eCommerce">
                                        Provincia
                                    </span>
                                </a>
                            </li>
                            <li class="nav-item {{ request()->is('zone') ? 'active' : '' }}">
                                <a href="{{route('zone.view')}}">
                                    <i class="fad fa-map-marked-alt"></i>
                                    <span class="menu-title" data-i18n="eCommerce">
                                        Zonas
                                    </span>
                                </a>
                            </li>
                            <li class="nav-item {{ request()->is('community') ? 'active' : '' }}">
                                <a href="{{route('community.view')}}">
                                    <i class="fas fa-map-pin"></i>
                                    <span class="menu-title" data-i18n="eCommerce">
                                        Comunidades
                                    </span>
                                </a>
                            </li>
                        </ul>
                      </li>
                </ul>
              </li>
        </ul>
    </div>
</div>
<!-- END: Main Menu-->